# -*- coding: utf-8 -*-
"""Equipo_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GFKNeNbldoQwA5Q9VeBnG7ld2mV1CCkb
"""

class Automaton:
    def __init__(self):
        self.states = {
            'Q0': {'letter': 'Q1', 'number': 'Qr', 'other': 'Qr'},
            'Q1': {'letter': 'Q2', 'number': 'Qr', 'other': 'Qr'},
            'Q2': {'letter': 'Q3', 'number': 'Qr', 'other': 'Qr'},
            'Q3': {'letter': 'Q4', 'number': 'Qr', 'other': 'Qr'},
            'Q4': {'letter': 'Qr', 'number': 'Q5', 'other': 'Qr'},
            'Q5': {'letter': 'Qr', 'number': 'Q6', 'other': 'Qr'},
            'Q6': {'letter': 'Qr', 'number': 'Q7', 'other': 'Qr'},
            'Q7': {'letter': 'Qr', 'number': 'Q8', 'other': 'Qr'},
            'Q8': {'letter': 'Qr', 'number': 'Q9', 'other': 'Qr'},
            'Q9': {'letter': 'Qr', 'number': 'Q10', 'other': 'Qr'},
            'Q10': {'letter': 'Q11', 'number': 'Q11', 'other': 'Qr'},
            'Q11': {'letter': 'Q12', 'number': 'Q12', 'other': 'Qr'},
            'Q12': {'letter': 'Q12', 'number': 'Q12', 'other': 'Qr'},
            'Qr': {}
        }
        self.accept_states = ['Q12']

    def check_string(self, string):
        current_state = 'Q0'
        for character in string:
            if character.isalpha():
                current_state = self.states[current_state].get('letter', 'Qr')
            elif character.isdigit():
                current_state = self.states[current_state].get('number', 'Qr')
            else:
                current_state = self.states[current_state].get('other', 'Qr')

        return current_state in self.accept_states

automaton = Automaton()
rfc = input('Introduce un RFC: ')
print(automaton.check_string(rfc.upper()))